package com.evernox.controller;

import com.evernox.common.Result;
import com.evernox.common.ResultCode;
import com.evernox.dto.ArenaCategoryOption;
import com.evernox.dto.ArenaFilterOptions;
import com.evernox.dto.ArenaRankItem;
import com.evernox.dto.ArenaSyncStatus;
import com.evernox.exception.BusinessException;
import com.evernox.service.AiArenaCrawler;
import com.evernox.service.AiArenaService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * Code Arena 模型排行榜接口（查询对登录用户开放，同步/导入仅管理员）
 */
@RestController
@RequestMapping("/ai-arena")
@RequiredArgsConstructor
public class AiArenaController {

    /** 数据包内单个页面 HTML 的上限，防止解压炸弹（正常榜单页约 1.4MB） */
    private static final int MAX_HTML_BYTES = 8 * 1024 * 1024;

    /** 下载下来的本地抓取脚本文件名 */
    private static final String FETCHER_FILE_NAME = "fetch-arena-leaderboard.bat";

    /** 分类数组占位符，由 AiArenaCrawler.CATEGORIES 填入 */
    private static final String SLUGS_PLACEHOLDER = "@SLUGS@";

    /**
     * 单文件抓取脚本模板（一个 .bat 同时被 cmd 与 PowerShell 解析）。
     *
     * 【为什么能混排】cmd 执行到 `exit /b %ERRORLEVEL%` 就结束，标记行
     * `#==PS-BELOW==#` 之后的 PowerShell 正文它永远不会解析，所以正文里可以
     * 自由使用 () & | 等 cmd 特殊字符。PowerShell 侧则把本文件整体按 UTF-8 读出来，
     * 取标记之后的部分 Invoke-Expression。
     *
     * 【几处不能改的细节】
     *  - 启动头必须是纯 ASCII：cmd 按 OEM 代码页读批处理，写中文会乱码。
     *  - 路径经 `%ARENA_SELF` 环境变量传给 PowerShell，不拼进命令行——
     *    脚本路径含空格或中文时，拼进 -Command 会把命令行截断。
     *  - loader 行自身也含标记串，所以用 LastIndexOf 从后往前找，命中的才是真标记行。
     *  - 整份模板不含任何密钥；它是公开下载物。
     */
    private static final String FETCHER_SCRIPT_TEMPLATE = """
            @echo off
            setlocal
            REM ============================================================
            REM  EverNox Studio - Code Arena leaderboard fetcher, single file
            REM
            REM  Generated by the EverNox backend from AiArenaCrawler.CATEGORIES.
            REM  Do not edit by hand; download a fresh copy from the website.
            REM
            REM  arena.ai blocks the cloud server datacenter IP with HTTP 403, so the
            REM  pages are downloaded here and then imported on the website page
            REM  AI / Model Leaderboard / Import package. Parsing stays on the server.
            REM
            REM  USAGE: double-click this file.
            REM ============================================================
            set "ARENA_SELF=%~f0"
            powershell -NoProfile -ExecutionPolicy Bypass -Command "$t=[IO.File]::ReadAllText($env:ARENA_SELF,[Text.Encoding]::UTF8);$m='#==PS-BELOW==#';$i=$t.LastIndexOf($m);Invoke-Expression $t.Substring($i+$m.Length)"
            exit /b %ERRORLEVEL%
            #==PS-BELOW==#
            $ErrorActionPreference = 'Stop'
            $ProgressPreference = 'SilentlyContinue'

            $base = 'https://arena.ai/leaderboard/code/webdev/'
            $slugs = @(@SLUGS@)

            $headers = @{
                'User-Agent'      = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36'
                'Accept'          = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8'
                'Accept-Language' = 'en-US,en;q=0.9'
            }

            $scriptDir = Split-Path -Parent $env:ARENA_SELF
            $stamp = Get-Date -Format 'yyyyMMdd-HHmm'
            $workDir = Join-Path $env:TEMP "arena-lb-$stamp"
            $zipPath = Join-Path $scriptDir "arena-lb-$stamp.zip"

            New-Item -ItemType Directory -Path $workDir -Force | Out-Null

            Write-Host ''
            Write-Host "Downloading $($slugs.Count) category pages from arena.ai ..." -ForegroundColor Cyan

            $failed = @()
            foreach ($slug in $slugs) {
                $file = Join-Path $workDir "$slug.html"
                try {
                    Invoke-WebRequest -Uri "$base$slug" -Headers $headers -UseBasicParsing -TimeoutSec 60 -OutFile $file
                    $text = Get-Content $file -Raw
                    if ($text.Length -lt 50000 -or $text.IndexOf('<table') -lt 0) {
                        $failed += $slug
                        Write-Host ("  [bad]  {0} - page looks incomplete, skipped" -f $slug) -ForegroundColor Yellow
                        Remove-Item $file -Force -ErrorAction SilentlyContinue
                    } else {
                        Write-Host ("  [ok]   {0}" -f $slug)
                    }
                } catch {
                    $failed += $slug
                    Write-Host ("  [fail] {0} - {1}" -f $slug, $_.Exception.Message) -ForegroundColor Yellow
                }
            }

            $okCount = $slugs.Count - $failed.Count
            if ($okCount -eq 0) {
                Write-Host ''
                Write-Host 'All downloads failed: this machine cannot reach arena.ai either.' -ForegroundColor Red
                Write-Host 'Nothing was packaged.' -ForegroundColor Red
                exit 1
            }

            if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
            Compress-Archive -Path (Join-Path $workDir '*.html') -DestinationPath $zipPath -CompressionLevel Optimal

            $sizeMb = [math]::Round((Get-Item $zipPath).Length / 1MB, 2)

            Write-Host ''
            Write-Host ("Package ready: {0}" -f $zipPath) -ForegroundColor Green
            Write-Host ("  {0}/{1} categories, {2} MB" -f $okCount, $slugs.Count, $sizeMb) -ForegroundColor Green
            if ($failed.Count -gt 0) {
                Write-Host ("  Missing (old data will be kept for them): {0}" -f ($failed -join ', ')) -ForegroundColor Yellow
            }
            Write-Host ''
            Write-Host 'Next: open the website, go to AI / Model Leaderboard,' -ForegroundColor Cyan
            Write-Host '      click "Import package" and pick the zip file printed above.' -ForegroundColor Cyan
            Write-Host ''
            exit 0
            """;

    private final AiArenaService aiArenaService;

    @GetMapping("/categories")
    public Result<List<ArenaCategoryOption>> categories() {
        return Result.success(aiArenaService.listCategories());
    }

    @GetMapping("/items")
    public Result<List<ArenaRankItem>> items(
            @RequestParam String category,
            @RequestParam(required = false) String org,
            @RequestParam(required = false) String priceType,
            @RequestParam(required = false) Double minPrice,
            @RequestParam(required = false) Double maxPrice,
            @RequestParam(required = false) String keyword) {
        return Result.success(aiArenaService.listItems(category, org, priceType, minPrice, maxPrice, keyword));
    }

    @GetMapping("/filters")
    public Result<ArenaFilterOptions> filters(@RequestParam String category) {
        return Result.success(aiArenaService.getFilterOptions(category));
    }

    @GetMapping("/sync/status")
    public Result<ArenaSyncStatus> syncStatus() {
        return Result.success(aiArenaService.getSyncStatus());
    }

    /** 服务器直连官网抓取（官网 CDN 拦截机房 IP 时会返回 403，此时改用 /import） */
    @PostMapping("/sync")
    @PreAuthorize("hasRole('admin')")
    public Result<Void> sync() {
        aiArenaService.triggerSyncAsync();
        return Result.<Void>success("已开始同步", null);
    }

    /**
     * 导入「本地抓取 → 打包上传」的榜单数据包（zip，条目名形如 overall.html）。
     * 用于服务器 IP 被官网风控拦截（403）的场景：本地脚本负责下载页面，
     * 服务端负责解析入库，解析规则只有 AiArenaCrawler 一份。
     */
    @PostMapping(value = "/import", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @PreAuthorize("hasRole('admin')")
    public Result<ArenaSyncStatus> importPackage(@RequestParam("file") MultipartFile file) {
        ArenaSyncStatus status = aiArenaService.importHtml(readHtmlPackage(file));
        return Result.success(status.isLastSuccess() ? "导入完成" : "导入未成功", status);
    }

    /**
     * 下载「本地抓取」用的单文件脚本。
     *
     * 服务器是机房 IP，会被 arena.ai 的 CDN/WAF 判成爬虫返回 403，抓取只能发生在
     * 能正常访问官网的机器上。脚本由本接口按需生成（而不是仓库里存一份），
     * 这样分类列表永远等于 {@link AiArenaCrawler#CATEGORIES}，不会出现两边漂移。
     * 脚本里不含任何密钥，只负责下载页面，解析仍在服务端 {@link AiArenaCrawler}。
     */
    @GetMapping(value = "/fetcher", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
    @PreAuthorize("hasRole('admin')")
    public ResponseEntity<byte[]> fetcher() {
        byte[] body = buildFetcherScript().getBytes(StandardCharsets.UTF_8);
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + FETCHER_FILE_NAME + "\"")
                .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_OCTET_STREAM_VALUE)
                .contentLength(body.length)
                .body(body);
    }

    /** 用 CATEGORIES 填充分类数组，生成脚本正文（UTF-8，不带 BOM，否则 cmd 解析首行会报错） */
    private String buildFetcherScript() {
        String slugs = AiArenaCrawler.CATEGORIES.stream()
                .map(c -> "'" + c.slug() + "'")
                .collect(Collectors.joining(", "));
        return FETCHER_SCRIPT_TEMPLATE.replace(SLUGS_PLACEHOLDER, slugs);
    }

    /** 读取 zip 数据包，返回 分类slug → 页面 HTML；只识别已知分类的文件名 */
    private Map<String, String> readHtmlPackage(MultipartFile file) {
        if (file == null || file.isEmpty()) {
            throw new BusinessException(ResultCode.PARAM_ERROR, "请选择要导入的数据包");
        }
        Map<String, String> result = new LinkedHashMap<>();
        try (ZipInputStream zis = new ZipInputStream(file.getInputStream(), StandardCharsets.UTF_8)) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                if (entry.isDirectory()) {
                    continue;
                }
                String fileName = baseName(entry.getName());
                AiArenaCrawler.Category category = AiArenaCrawler.categoryBySlug(stripExtension(fileName));
                if (category == null) {
                    continue;
                }
                byte[] bytes = zis.readNBytes(MAX_HTML_BYTES + 1);
                if (bytes.length > MAX_HTML_BYTES) {
                    throw new BusinessException(ResultCode.PARAM_ERROR, "数据包内单个页面过大：" + fileName);
                }
                result.put(category.slug(), new String(bytes, StandardCharsets.UTF_8));
            }
        } catch (IOException e) {
            throw new BusinessException(ResultCode.PARAM_ERROR, "数据包读取失败：" + e.getMessage());
        }
        if (result.isEmpty()) {
            throw new BusinessException(ResultCode.PARAM_ERROR,
                    "数据包里没有可识别的分类页面（文件名应为 overall.html、frontend.html 等，请用 fetch-arena-leaderboard 脚本生成）");
        }
        return result;
    }

    private static String baseName(String path) {
        int slash = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'));
        return slash >= 0 ? path.substring(slash + 1) : path;
    }

    private static String stripExtension(String fileName) {
        int dot = fileName.lastIndexOf('.');
        return dot > 0 ? fileName.substring(0, dot) : fileName;
    }
}
