/**
 * 项目实际用到的 Element Plus 图标（78 个）。
 *
 * 为什么需要这个文件：图标不在 unplugin-vue-components 的 ElementPlusResolver 覆盖范围内，
 * 所以模板里 `<Trophy />` 这类写法依赖**全局注册**（`app.component('Trophy', ...)`）。
 * 但原来 main.ts 是 `import * as` 注册全部 293 个，那会让整个图标包进 bundle。
 * 这里显式 re-export 用到的这些，打包时才能 tree-shake 掉没用的。
 *
 * 维护约定：新增图标时把名字加进下面的清单；漏加的表现是"图标不显示"（不报错），
 * 所以改完模板请顺手确认一下。
 */
export {
  Aim,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Bell,
  Box,
  Brush,
  Calendar,
  ChatDotRound,
  Check,
  CircleCheck,
  CirclePlusFilled,
  Clock,
  Close,
  Cloudy,
  Coin,
  Collection,
  CollectionTag,
  Compass,
  Cpu,
  DataAnalysis,
  DataLine,
  Delete,
  Document,
  Download,
  Edit,
  EditPen,
  Expand,
  Filter,
  FirstAidKit,
  Flag,
  Fold,
  Folder,
  FolderOpened,
  FullScreen,
  Grid,
  Hide,
  HomeFilled,
  Link,
  List,
  Loading,
  Location,
  Lock,
  Medal,
  Money,
  Moon,
  MoreFilled,
  Notebook,
  PartlyCloudy,
  Picture,
  PictureFilled,
  PictureRounded,
  Plus,
  Pointer,
  Position,
  Promotion,
  QuestionFilled,
  Refresh,
  Search,
  Setting,
  Star,
  StarFilled,
  SwitchButton,
  Ticket,
  Timer,
  TopRight,
  TrendCharts,
  Trophy,
  Unlock,
  Upload,
  UploadFilled,
  User,
  UserFilled,
  VideoPlay,
  View,
  Wallet,
  WarningFilled,
  ZoomIn,
} from '@element-plus/icons-vue'
